import { StyleSheet } from 'react-native';
import { colors, typography } from '../../theme';

export const styles = StyleSheet.create({
  fixedHeader: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 12 },
  content: { paddingHorizontal: 20, paddingTop: 12, gap: 12 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  greeting: { flex: 1 },
  menuButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: colors.sunlightSoft,
  },
  headerName: { fontSize: 26, lineHeight: 34 },
  financeCard: {
    padding: 16,
    gap: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 18,
  },
  financeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    gap: 8,
  },
  financeLink: { flex: 1, minHeight: 44, justifyContent: 'center', gap: 4 },
  financeActions: { flexDirection: 'row' },
  financeIconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  featureTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    color: colors.ink,
  },
  balance: {
    padding: 14,
    gap: 4,
    borderRadius: 14,
    backgroundColor: colors.skySoft,
  },
  balanceLabel: { ...typography.small, color: colors.sky },
  balanceAmount: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '700',
    color: colors.ink,
  },
  totals: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 },
  total: { flexGrow: 1, flexBasis: 110, gap: 4 },
  totalAmount: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
    color: colors.ink,
  },
  localNotice: { ...typography.small, fontSize: 11, color: colors.sunlight },
  recoveryNotice: { ...typography.small, fontSize: 11, color: colors.sky },
  error: { ...typography.small, color: colors.danger },
  loading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 16,
  },
});
