import { StyleSheet } from 'react-native';
import { colors, typography } from '../../theme';

export const styles = StyleSheet.create({
  header: { paddingHorizontal: 20, paddingTop: 16 },
  content: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
    gap: 14,
  },
  month: { ...typography.small, color: colors.muted },
  summary: {
    gap: 14,
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  balance: {
    gap: 4,
    padding: 14,
    borderRadius: 14,
    backgroundColor: colors.skySoft,
  },
  balanceLabel: { ...typography.small, color: colors.sky },
  balanceAmount: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '700',
    color: colors.ink,
  },
  totals: { flexDirection: 'row', gap: 12 },
  total: { flex: 1, gap: 3 },
  totalLabel: { ...typography.small, fontSize: 12 },
  income: { color: colors.success },
  expense: { color: colors.earth },
  totalAmount: { fontSize: 15, fontWeight: '700', color: colors.ink },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: { ...typography.heading, fontSize: 18, lineHeight: 24 },
  transactionList: { gap: 10 },
  transaction: {
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  transactionIcon: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
  },
  incomeIcon: { backgroundColor: '#EAF2EC' },
  expenseIcon: { backgroundColor: colors.sunlightSoft },
  transactionText: { flex: 1, gap: 2 },
  transactionTitle: { fontSize: 15, fontWeight: '600', color: colors.ink },
  transactionNote: { ...typography.small, fontSize: 12 },
  transactionDate: { ...typography.small, fontSize: 11 },
  transactionAmount: { fontSize: 14, fontWeight: '700' },
  deleteButton: {
    width: 38,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  empty: {
    alignItems: 'center',
    gap: 6,
    paddingVertical: 28,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  emptyTitle: { ...typography.body, color: colors.ink, fontWeight: '600' },
  feedback: { ...typography.small, color: colors.danger },
});
