import { StyleSheet } from 'react-native';
import { colors, typography } from '../../theme';

export const styles = StyleSheet.create({
  header: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 12, gap: 8 },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  headerTitle: { fontSize: 26, lineHeight: 34 },
  addButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: colors.sunlightSoft,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 28,
    gap: 14,
  },
  searchInput: {
    minHeight: 46,
    paddingHorizontal: 14,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.line,
    color: colors.ink,
    backgroundColor: colors.surface,
  },
  searchResults: { gap: 10 },
  reportMode: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: 15,
    backgroundColor: colors.skySoft,
  },
  reportModeButton: {
    flex: 1,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
  },
  reportModeSelected: {
    backgroundColor: colors.surface,
    shadowColor: colors.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 1,
  },
  reportModeText: { fontSize: 14, fontWeight: '600', color: colors.muted },
  reportModeTextSelected: { color: colors.earth },
  month: { ...typography.small, color: colors.muted },
  syncStatus: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#EAF2EC',
  },
  syncPending: {
    flexWrap: 'wrap',
    paddingVertical: 6,
    backgroundColor: colors.sunlightSoft,
  },
  syncRecovery: {
    flexWrap: 'wrap',
    paddingVertical: 6,
    backgroundColor: colors.skySoft,
  },
  syncText: {
    flex: 1,
    ...typography.small,
    fontSize: 11,
    color: colors.success,
  },
  syncPendingText: { color: colors.sunlight },
  syncRecoveryText: { color: colors.sky },
  summary: {
    gap: 14,
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  balance: {
    gap: 4,
    padding: 14,
    borderRadius: 14,
    backgroundColor: colors.skySoft,
  },
  balanceLabel: { ...typography.small, color: colors.sky },
  balanceAmount: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '700',
    color: colors.ink,
  },
  totals: { flexDirection: 'row', gap: 12 },
  total: { flex: 1, gap: 3 },
  totalLabel: { ...typography.small, fontSize: 12 },
  income: { color: colors.success },
  expense: { color: colors.earth },
  totalAmount: { fontSize: 15, fontWeight: '700', color: colors.ink },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: { ...typography.heading, fontSize: 18, lineHeight: 24 },
  monthList: { gap: 16 },
  monthSection: {
    gap: 10,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  monthHeader: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  monthTextBlock: { flex: 1, gap: 2 },
  monthTitle: { ...typography.body, color: colors.ink, fontWeight: '700' },
  monthTotals: { ...typography.small, fontSize: 11 },
  monthBalanceBlock: { alignItems: 'flex-end', gap: 2 },
  monthBalanceLabel: { ...typography.small, fontSize: 10 },
  monthBalance: { fontSize: 13, fontWeight: '700', color: colors.earth },
  monthAddButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: colors.primarySoft,
  },
  transactionList: { gap: 10 },
  transaction: {
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  transactionIcon: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  incomeIcon: { backgroundColor: '#EAF2EC' },
  expenseIcon: { backgroundColor: colors.sunlightSoft },
  transactionText: { flex: 1, gap: 2 },
  transactionTitle: { fontSize: 15, fontWeight: '600', color: colors.ink },
  transactionNote: { ...typography.small, fontSize: 12 },
  transactionDate: { ...typography.small, fontSize: 11 },
  transactionAmount: { fontSize: 14, fontWeight: '700' },
  deleteButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  empty: {
    alignItems: 'center',
    gap: 6,
    paddingVertical: 28,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  emptyTitle: { ...typography.body, color: colors.ink, fontWeight: '600' },
  feedback: { ...typography.small, color: colors.danger },
});
