import { StyleSheet } from 'react-native';
import { colors, typography } from '../../theme';

export const categoryReportStyles = StyleSheet.create({
  container: { gap: 14 },
  periodCard: {
    gap: 8,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  periodHint: { ...typography.small, fontSize: 11, textAlign: 'center' },
  modeSwitch: {
    flexDirection: 'row',
    padding: 3,
    borderRadius: 13,
    backgroundColor: colors.skySoft,
  },
  modeButton: {
    flex: 1,
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    borderRadius: 10,
  },
  modeSelected: { backgroundColor: colors.surface },
  modeText: { fontSize: 13, fontWeight: '600', color: colors.muted },
  modeTextSelected: { color: colors.earth },
  yearPicker: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  yearArrow: {
    width: 44,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  yearText: {
    ...typography.heading,
    minWidth: 88,
    textAlign: 'center',
    fontSize: 20,
  },
  rangeRow: { flexDirection: 'row', gap: 10 },
  rangeButton: {
    flex: 1,
    minHeight: 58,
    justifyContent: 'center',
    gap: 3,
    paddingHorizontal: 11,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.background,
  },
  rangeLabel: { ...typography.small, fontSize: 11 },
  rangeValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 3,
  },
  rangeValue: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  summaryCard: {
    overflow: 'hidden',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  totalCard: {
    gap: 5,
    padding: 16,
    backgroundColor: colors.skySoft,
  },
  expenseTotalCard: { backgroundColor: colors.sunlightSoft },
  totalLabel: { ...typography.small, color: colors.sky, fontWeight: '600' },
  totalAmount: {
    fontSize: 24,
    lineHeight: 32,
    fontVariant: ['tabular-nums'],
    fontWeight: '700',
    color: colors.ink,
  },
  expenseTotalAmount: { color: colors.earth },
  periodBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 2,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  periodBadgeText: { fontSize: 11, fontWeight: '600', color: colors.sky },
  categoryTotals: { paddingHorizontal: 15, paddingVertical: 5 },
  categoryTotalRow: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  categoryNameRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  categoryDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.earthLight,
  },
  expenseCategoryDot: { backgroundColor: colors.sunlight },
  categoryName: { ...typography.small, fontSize: 13, color: colors.ink },
  categoryAmount: { fontSize: 13, fontWeight: '700', color: colors.earth },
  detailsHeading: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 8,
  },
  detailsTitle: { ...typography.heading, fontSize: 18, lineHeight: 24 },
  monthCount: { ...typography.small, fontSize: 11 },
  monthList: { gap: 10 },
  monthCard: {
    gap: 10,
    padding: 11,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  monthHeader: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  monthSummary: {
    flex: 1,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  monthMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  monthNameBlock: { flex: 1, gap: 2 },
  monthName: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  monthBreakdown: { ...typography.small, fontSize: 10 },
  monthTotal: {
    color: colors.success,
    fontSize: 13,
    fontWeight: '700',
  },
  expenseMonthTotal: { color: colors.earth },
  monthAddButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: colors.primarySoft,
  },
  transactionList: { gap: 8 },
  emptyState: {
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 18,
    paddingVertical: 26,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  emptyIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: colors.skySoft,
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyHint: { ...typography.small, fontSize: 11, textAlign: 'center' },
  dialog: { maxHeight: '84%', padding: 20, gap: 14 },
  dialogTitle: { ...typography.heading, fontSize: 19, lineHeight: 26 },
  dialogYearRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogYearArrow: {
    width: 42,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogYear: {
    minWidth: 86,
    color: colors.ink,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  monthGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 8,
  },
  monthChoice: {
    width: '31.5%',
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  monthSelected: {
    borderColor: colors.primaryBorder,
    backgroundColor: colors.primarySoft,
  },
  monthChoiceText: { fontSize: 12, color: colors.muted },
  monthChoiceTextSelected: { color: colors.earth, fontWeight: '700' },
});
