import { StyleSheet } from 'react-native';
import { colors, typography } from '../../theme';

export const styles = StyleSheet.create({
  card: {
    gap: 7,
    padding: 9,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  monthNavigation: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  navigationButton: {
    width: 38,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  selectedMonthButton: {
    flex: 1,
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: colors.primarySoft,
  },
  selectedMonthText: { color: colors.ink, fontSize: 15, fontWeight: '700' },
  currentMonthButton: {
    alignSelf: 'center',
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: 9,
    borderRadius: 10,
    backgroundColor: colors.skySoft,
  },
  currentMonthText: { color: colors.sky, fontSize: 11, fontWeight: '600' },
  yearRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  yearButton: {
    width: 42,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  year: {
    ...typography.heading,
    fontSize: 19,
    lineHeight: 26,
    minWidth: 74,
    textAlign: 'center',
  },
  dialog: { maxHeight: '80%', padding: 20, gap: 14 },
  dialogTitle: { ...typography.heading, fontSize: 19, lineHeight: 26 },
  monthGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  monthChoice: {
    width: '31%',
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  monthSelected: {
    borderColor: colors.primaryBorder,
    backgroundColor: colors.primarySoft,
  },
  monthChoiceText: { fontSize: 13, color: colors.muted },
  monthChoiceTextSelected: { color: colors.earth, fontWeight: '700' },
});
