import { StyleSheet } from 'react-native';
import { colors, typography } from '../../theme';

export const styles = StyleSheet.create({
  header: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  back: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { flex: 1 },
  add: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: colors.sunlightSoft,
  },
  fixedHeader: { paddingHorizontal: 18, paddingTop: 8, paddingBottom: 12 },
  content: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 32,
    gap: 10,
  },
  taskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 10,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 15,
    backgroundColor: colors.surface,
  },
  check: {
    width: 36,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskText: { flex: 1, gap: 3 },
  taskTitle: { ...typography.body, color: colors.ink, fontWeight: '600' },
  completed: { color: colors.muted, textDecorationLine: 'line-through' },
  taskDetails: { ...typography.small, color: colors.ink },
  taskActions: { flexDirection: 'row' },
  action: {
    width: 34,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  empty: {
    alignItems: 'center',
    gap: 8,
    padding: 26,
    borderRadius: 16,
    backgroundColor: colors.surface,
  },
  emptyTitle: { ...typography.heading, fontSize: 17 },
  sync: { ...typography.small, fontSize: 11, color: colors.success },
  syncLocal: { color: colors.sunlight },
  error: { ...typography.small, color: colors.danger },
  dialog: { gap: 13, padding: 20 },
  dialogTitle: { ...typography.heading, color: colors.ink },
  input: {
    minHeight: 46,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 12,
    color: colors.ink,
    backgroundColor: colors.surface,
  },
  details: { minHeight: 86, paddingTop: 10 },
  dateRow: { flexDirection: 'row', gap: 8 },
  dateInput: { flex: 1 },
  timeInput: { width: 92 },
  fieldLabel: { ...typography.small, color: colors.ink, fontWeight: '600' },
  reminderToggle: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 5,
  },
  flex: { flex: 1 },
});
