import { StyleSheet } from 'react-native';
import { colors, typography } from '../../theme';

export const styles = StyleSheet.create({
  fixedHeader: { paddingHorizontal: 20, paddingTop: 16 },
  content: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 20,
    gap: 14,
  },
  profileCard: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  profileText: { flex: 1, gap: 2 },
  profileName: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    color: colors.ink,
  },
  card: {
    gap: 12,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  notificationRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  notificationText: { flex: 1, gap: 2 },
  cardTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
    color: colors.ink,
  },
  iconBadge: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
  },
  notificationIcon: { backgroundColor: colors.skySoft },
  accountIcon: { backgroundColor: colors.dangerSoft },
  accountCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
  },
  accountText: { flex: 1, gap: 2 },
  error: { ...typography.small, color: colors.danger },
  footer: {
    marginTop: 'auto',
    fontSize: 12,
    lineHeight: 18,
    color: colors.muted,
    textAlign: 'center',
    paddingTop: 2,
  },
});
