import { StyleSheet } from 'react-native';
import { colors } from '../../theme';

export const styles = StyleSheet.create({
  header: { gap: 12 },
  flex: { flex: 1 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  importBox: {
    backgroundColor: colors.cream,
    borderRadius: 22,
    padding: 20,
    gap: 16,
  },
  importIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  empty: { alignItems: 'center', gap: 20, paddingVertical: 40 },
  description: {
    fontSize: 15,
    lineHeight: 24,
    textAlign: 'center',
    color: colors.muted,
  },
  list: { gap: 12 },
  track: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.line,
  },
  trackSelected: { borderColor: colors.green },
  trackTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.ink,
    marginBottom: 4,
  },
  icon: {
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  order: {
    width: 28,
    height: 28,
    textAlign: 'center',
    lineHeight: 28,
    borderRadius: 8,
    backgroundColor: colors.green,
    color: colors.surface,
    fontWeight: '700',
  },
  action: {
    minHeight: 44,
    paddingHorizontal: 8,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
  },
  actionText: { color: colors.green, fontWeight: '600' },
  sync: { fontSize: 12, color: colors.green },
  selection: {
    gap: 12,
    padding: 16,
    backgroundColor: colors.primarySoft,
    borderRadius: 16,
  },
  notice: {
    gap: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 16,
  },
  error: { color: colors.danger, lineHeight: 22 },
  message: { color: colors.green, lineHeight: 22 },
});
