import { StyleSheet } from 'react-native';
import { colors } from '../../theme';

export const styles = StyleSheet.create({
  mp3FixedHeader: { paddingTop: 8, paddingBottom: 8 },
  mp3HeaderTitle: { fontSize: 26, lineHeight: 32 },
  fixedMp3Content: { gap: 12 },
  flex: { flex: 1 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  importSection: { gap: 12 },
  importDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.muted,
  },
  importBox: {
    backgroundColor: colors.sunlightSoft,
    borderRadius: 20,
    padding: 16,
    gap: 12,
  },
  importIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  importTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    color: colors.ink,
  },
  importDetail: { fontSize: 12, lineHeight: 18, color: colors.muted },
  importFootnote: { fontSize: 12, lineHeight: 18, color: colors.muted },
  backupNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    backgroundColor: colors.skySoft,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
  },
  backupIcon: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: colors.surface,
  },
  backupText: { flex: 1, gap: 2 },
  backupTitle: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    color: colors.ink,
  },
  backupDetail: { fontSize: 12, lineHeight: 18, color: colors.muted },
  empty: { alignItems: 'center', gap: 20, paddingVertical: 40 },
  description: {
    fontSize: 15,
    lineHeight: 24,
    textAlign: 'center',
    color: colors.muted,
  },
  list: { gap: 12 },
  track: {
    position: 'relative',
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.line,
  },
  trackSelected: { borderColor: colors.primaryBorder },
  trackTopRow: { paddingRight: 56 },
  trackDelete: {
    position: 'absolute',
    right: 0,
    top: '50%',
    width: 44,
    height: 44,
    transform: [{ translateY: -22 }],
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  trackTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.ink,
    marginBottom: 4,
    flexShrink: 1,
  },
  trackTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  titleControl: {
    height: 36,
    flexShrink: 1,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  marqueeHiddenTitle: { opacity: 0 },
  marqueeContent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  marqueeCopy: { flexDirection: 'row', flexShrink: 0 },
  marqueeSeparator: { height: 1 },
  marqueeMeasure: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 1,
    height: 1,
    opacity: 0,
  },
  marqueeInactive: { opacity: 0 },
  marqueeText: { flexShrink: 0 },
  titleIcon: {
    minWidth: 20,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon: {
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  order: {
    width: 28,
    height: 28,
    textAlign: 'center',
    lineHeight: 28,
    borderRadius: 8,
    backgroundColor: colors.primary,
    color: colors.onPrimary,
    fontWeight: '700',
  },
  action: {
    minHeight: 44,
    paddingHorizontal: 6,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
  },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  actionText: { color: colors.earth, fontWeight: '600' },
  sync: { fontSize: 12, color: colors.success },
  selection: {
    gap: 12,
    padding: 16,
    backgroundColor: colors.primarySoft,
    borderRadius: 16,
  },
  errorNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 12,
    backgroundColor: colors.dangerSoft,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 18,
  },
  errorIcon: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: colors.surface,
  },
  errorText: { flex: 1, gap: 2 },
  error: { color: colors.danger, lineHeight: 22 },
  errorDetail: { fontSize: 12, lineHeight: 18, color: colors.muted },
  libraryIconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: colors.sunlightSoft,
  },
  queueItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 8,
    paddingLeft: 8,
    paddingRight: 4,
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
  },
  queueDragging: {
    borderColor: colors.earth,
    backgroundColor: colors.primarySoft,
    shadowColor: colors.earth,
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
  },
  queueMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 52,
  },
  queueIndex: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  queueReorderHandle: {
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
  },
  queueReorderHandleDragging: { backgroundColor: colors.sunlightSoft },
  queueIndicator: { position: 'absolute', left: 2, top: 2 },
  hiddenIndicator: { opacity: 0 },
  queueNumber: { color: colors.muted, fontWeight: '700', fontSize: 16 },
  repeatOn: {
    backgroundColor: colors.sunlightSoft,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.sunlightBorder,
  },
  message: { color: colors.success, lineHeight: 22 },
});
